[package]
name = "liquids-separation"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = "0.6.0"
itertools = "0.14.0"
rand = "0.9.1"

[[bench]]
name = "separate_liquids_bench"
harness = false
